create table if not exists "divisionOfExpenses".event
(
    id bigint generated by default as identity
        constraint event_pkey
            primary key,
    create_date timestamp default current_timestamp,
    modify_date timestamp default current_timestamp,
    description varchar(255),
    event_date_time timestamp,
    name varchar(255),
    total_event_sum numeric(19, 2),
    shopping_list_id bigint
);

create table if not exists "divisionOfExpenses".roles
(
    id          bigint generated by default as identity
        constraint role_pkey
            primary key,
    create_date timestamp default current_timestamp,
    modify_date timestamp default current_timestamp,
    name        varchar(255)
);


create table if not exists "divisionOfExpenses".event_roles
(
    event_id bigint not null
        constraint fkfx69i4ow2qg2enkuokmxxiiyl
            references "divisionOfExpenses".event,
    roles_id bigint not null
        constraint uk_qydu3p9hsfvlkaxq1tvftf4b0
            unique
        constraint fkjj8oscnm538cgxdxlp3rr5evl
            references "divisionOfExpenses".roles
);

create table if not exists "divisionOfExpenses".shopping_list
(
    id           bigint generated by default as identity
        constraint shopping_list_pkey
            primary key,
    create_date  timestamp,
    modify_date  timestamp,
    comment      varchar(255),
    enabled_flag boolean,
    event_id     bigint
        constraint fkss1lu0q3tgd9rm59satrp7bjo
            references "divisionOfExpenses".event
);

alter table "divisionOfExpenses".event
    add constraint fkcaeoetktnp0k5au437rysqaef
        foreign key (shopping_list_id) references "divisionOfExpenses".shopping_list;

create table if not exists "divisionOfExpenses".shopping_list_item
(
    id                  bigint generated by default as identity
        constraint shopping_list_item_pkey
            primary key,
    create_date         timestamp,
    modify_date         timestamp,
    name                varchar(255),
    quantity            varchar(255),
    shoppinglistitem_id bigint
        constraint fkewo6pgiv4ap559xv2fkl4ejwt
            references "divisionOfExpenses".shopping_list
);

create table if not exists "divisionOfExpenses".users
(
    id          bigint generated by default as identity
        constraint user_entity_pkey
            primary key,
    create_date timestamp default current_timestamp,
    modify_date timestamp default current_timestamp,
    username    varchar(30) not null unique,
    password    varchar(80) not null,
    first_name  varchar(255),
    last_name   varchar(255)
);


create table if not exists "divisionOfExpenses".orders
(
    id              bigint generated by default as identity
        constraint orders_pkey
            primary key,
    create_date     timestamp,
    modify_date     timestamp,
    bill_photo      varchar(255),
    comment         varchar(255),
    order_date      timestamp,
    total_order_sum numeric(19, 2),
    buyer_id        bigint
        constraint fkjw4icr7byo4i7671al805xd5f
            references "divisionOfExpenses".users
);

create table if not exists "divisionOfExpenses".direct_payer
(
    id          bigint generated by default as identity
        constraint direct_payer_pkey
            primary key,
    create_date timestamp,
    modify_date timestamp,
    summa       double precision,
    order_id    bigint
        constraint fkmhye1upy99y0p27o094aroi64
            references "divisionOfExpenses".orders,
    user_id     bigint
        constraint fk7lcu63s35j20qg212qx8i852d
            references "divisionOfExpenses".users
);

create table if not exists "divisionOfExpenses".partitial_payer
(
    id          bigint generated by default as identity
        constraint partitial_payer_pkey
            primary key,
    create_date timestamp,
    modify_date timestamp,
    coefficient double precision,
    order_id    bigint
        constraint fktmbflfgesub9wwyoq0gcdcnew
            references "divisionOfExpenses".orders,
    user_id     bigint
        constraint fkmha6qf2a3xi4yf7v6tobe9y0
            references "divisionOfExpenses".users
);

create table if not exists "divisionOfExpenses".users_orders
(
    order_id bigint not null
        constraint fk3qw31hyschokomhckmxieglrc
            references "divisionOfExpenses".users,
    user_id  bigint not null
        constraint uk_mf679n92xfppdm65roapo95je
            unique
        constraint fkcqr54mudug04wh17ikfj63nwn
            references "divisionOfExpenses".orders
);

create table if not exists "divisionOfExpenses".users_roles
(
    role_id bigint not null
        constraint fkjtfkvtvgx1uprk65qb7g5p5n6
            references "divisionOfExpenses".users,
    user_id bigint not null
        constraint fk3v3jvtqrw4ilk71alv38tu3cu
            references "divisionOfExpenses".roles
);

insert into "divisionOfExpenses".roles (name)
values
('ROLE_USER'),
('ROLE_ADMIN');

insert into "divisionOfExpenses".users (password, username, first_name, last_name)
values
('$2y$12$03d0usVKKgPvmgt4dMfGLuyFgHUzTZw8w8vhrjR98ppMBRrpTbvTa', 'bob', 'bob', 'johnson'),
('$2y$12$03d0usVKKgPvmgt4dMfGLuyFgHUzTZw8w8vhrjR98ppMBRrpTbvTa', 'john', 'john', 'johnson');

insert into "divisionOfExpenses".users_roles (user_id, role_id)
values
(1, 1),
(2, 2);